### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#202]
From Jeff Chamblee:

Today I worked with Christian Mesh to install the ExoCTK code. We did the following.

**Using PIP to install ExoCTK**
`pip install -e git+https://github.com/ExoCTK/exoctk.git#egg=exoctk`

We also have to do: 
`pip install h5py astroquery`

**Setting up the Python 3.6 Environment**
`conda env -f environment-3.6.yml`

**Running the Code**
Then tried to run ExoCTK code to create a target visibility Bokeh visualization:
```
import exoctk
_, _, _, figure = exoctk.contam_visibility.visibilityPA.checkVisPA("210.802429", "54.34875")
```

But the code fails because : 
```
packages/pandas/plotting/converter.py", line 365, in __init_
self._tz._utcoffset = self._tz.utcoffset(None)
AttributeError: 'datetime.timezone' object has no attribute '_utcoffset'
```

The full stack trace is below.

We believe this means ExoCTK has a Python 3.7 feature making it fail in 3.6. We believe It will be much harder to upgrade ExoMast from 3.6 to 3.7 than for the ExoCTK team to make a change for 3.6.

**Requests of the ExoCTK team**
1. Can you make code changes to help us get the above code run to on Python 3.6 in our environment
2. We would prefer not to use the -e option in pip install. We think the setup.py setting zip_safe=False is causing the issue. Can it be changed?
3. Please add or correct dependencies for h5py and astroquery so that we do not have to do a separate command: `pip install h5py astroquery`

Thanks!
Jeff Chamblee

```
>>> _, _, _, figure = exoctk.contam_visibility.visibilityPA.checkVisPA("210.802429", "54.34875")
Using Equatorial Coordinates
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/internal/1/ASB/asb-deploy/tmp/src/exoctk/exoctk/contam_visibility/visibilityPA.py", line 191, in checkVisPA
    plt.plot(gdMasked, paMasked, color='k')
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2813, in plot
    is not None else {}), **kwargs)
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1611, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 393, in _grab_next_args
    yield from self._plot_args(this, kwargs)
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 370, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 204, in _xy_from_xy
    bx = self.axes.xaxis.update_units(x)
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/matplotlib/axis.py", line 1475, in update_units
    self.set_units(default)
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/matplotlib/axis.py", line 1548, in set_units
    self._update_axisinfo()
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/matplotlib/axis.py", line 1490, in _update_axisinfo
    info = self.converter.axisinfo(self.units, self)
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/pandas/plotting/_converter.py", line 351, in axisinfo
    majfmt = PandasAutoDateFormatter(majloc, tz=tz)
  File "/internal/1/ASB/conda/envs/foobar/lib/python3.6/site-packages/pandas/plotting/_converter.py", line 365, in __init__
    self._tz._utcoffset = self._tz.utcoffset(None)
AttributeError: 'datetime.timezone' object has no attribute '_utcoffset'
```

**Comment by bourque** [comment]
I can confirm that a python 3.5 and python 3.6 environment does throw this error.  However, a python 3.7 environment throws a different error:

```
In [3]: _, _, _, figure = exoctk.contam_visibility.visibilityPA.checkVisPA("210.802429", "54.34875")
Using Equatorial Coordinates
2019-02-11 13:46:33.398 python[95294:13373081] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fbf1dfa95a0
2019-02-11 13:46:33.401 python[95294:13373081] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fbf1dfa95a0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3dd362db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff64ecfc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3ddcedb4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff3dcac820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff3dcac1e8 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x0000000b165c531d TkpInit + 413
	6   libtk8.6.dylib                      0x0000000b1651d17e Initialize + 2622
	7   _tkinter.cpython-37m-darwin.so      0x0000000b12feca0f _tkinter_create + 1183
	8   python                              0x00000001000ec8b6 _PyMethodDef_RawFastCallKeywords + 230
	9   python                              0x000000010022cb47 call_function + 247
	10  python                              0x000000010022a684 _PyEval_EvalFrameDefault + 45284
	11  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	12  python                              0x00000001000eb577 _PyFunction_FastCallDict + 231
	13  python                              0x000000010016f0b1 slot_tp_init + 193
	14  python                              0x0000000100179091 type_call + 241
	15  python                              0x00000001000ec283 _PyObject_FastCallKeywords + 179
	16  python                              0x000000010022cbe4 call_function + 404
	17  python                              0x000000010022a778 _PyEval_EvalFrameDefault + 45528
	18  python                              0x00000001000ec078 function_code_fastcall + 120
	19  python                              0x000000010022cafe call_function + 174
	20  python                              0x000000010022a684 _PyEval_EvalFrameDefault + 45284
	21  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	22  python                              0x00000001000eb577 _PyFunction_FastCallDict + 231
	23  python                              0x00000001000ef4a2 method_call + 130
	24  python                              0x00000001000ecef2 PyObject_Call + 130
	25  python                              0x000000010022a8cf _PyEval_EvalFrameDefault + 45871
	26  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	27  python                              0x00000001000ec783 _PyFunction_FastCallKeywords + 195
	28  python                              0x000000010022cafe call_function + 174
	29  python                              0x000000010022a6bf _PyEval_EvalFrameDefault + 45343
	30  python                              0x00000001000ec078 function_code_fastcall + 120
	31  python                              0x000000010022cafe call_function + 174
	32  python                              0x000000010022a684 _PyEval_EvalFrameDefault + 45284
	33  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	34  python                              0x00000001000ec783 _PyFunction_FastCallKeywords + 195
	35  python                              0x000000010022cafe call_function + 174
	36  python                              0x000000010022a684 _PyEval_EvalFrameDefault + 45284
	37  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	38  python                              0x00000001002190bb builtin_exec + 347
	39  python                              0x00000001000ec8b6 _PyMethodDef_RawFastCallKeywords + 230
	40  python                              0x000000010022cb47 call_function + 247
	41  python                              0x000000010022a6bf _PyEval_EvalFrameDefault + 45343
	42  python                              0x00000001001059f4 gen_send_ex + 180
	43  python                              0x0000000100225837 _PyEval_EvalFrameDefault + 25239
	44  python                              0x00000001001059f4 gen_send_ex + 180
	45  python                              0x0000000100225837 _PyEval_EvalFrameDefault + 25239
	46  python                              0x00000001001059f4 gen_send_ex + 180
	47  python                              0x00000001000ec853 _PyMethodDef_RawFastCallKeywords + 131
	48  python                              0x00000001000f98c4 _PyMethodDescr_FastCallKeywords + 84
	49  python                              0x000000010022cbd7 call_function + 391
	50  python                              0x000000010022a5ee _PyEval_EvalFrameDefault + 45134
	51  python                              0x00000001000ec078 function_code_fastcall + 120
	52  python                              0x000000010022cafe call_function + 174
	53  python                              0x000000010022a6bf _PyEval_EvalFrameDefault + 45343
	54  python                              0x00000001000ec078 function_code_fastcall + 120
	55  python                              0x000000010022cafe call_function + 174
	56  python                              0x000000010022a5ee _PyEval_EvalFrameDefault + 45134
	57  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	58  python                              0x00000001000ec783 _PyFunction_FastCallKeywords + 195
	59  python                              0x000000010022cafe call_function + 174
	60  python                              0x000000010022a778 _PyEval_EvalFrameDefault + 45528
	61  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	62  python                              0x00000001000ec783 _PyFunction_FastCallKeywords + 195
	63  python                              0x000000010022cafe call_function + 174
	64  python                              0x000000010022a5ee _PyEval_EvalFrameDefault + 45134
	65  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	66  python                              0x00000001000ec783 _PyFunction_FastCallKeywords + 195
	67  python                              0x000000010022cafe call_function + 174
	68  python                              0x000000010022a5ee _PyEval_EvalFrameDefault + 45134
	69  python                              0x00000001000ec078 function_code_fastcall + 120
	70  python                              0x000000010022cafe call_function + 174
	71  python                              0x000000010022a5ee _PyEval_EvalFrameDefault + 45134
	72  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	73  python                              0x00000001000eb577 _PyFunction_FastCallDict + 231
	74  python                              0x00000001000ef4a2 method_call + 130
	75  python                              0x00000001000ecef2 PyObject_Call + 130
	76  python                              0x000000010022a8cf _PyEval_EvalFrameDefault + 45871
	77  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	78  python                              0x00000001000ec783 _PyFunction_FastCallKeywords + 195
	79  python                              0x000000010022cafe call_function + 174
	80  python                              0x000000010022a6bf _PyEval_EvalFrameDefault + 45343
	81  python                              0x000000010021e2d2 _PyEval_EvalCodeWithName + 418
	82  python                              0x0000000100282c40 PyRun_FileExFlags + 256
	83  python                              0x00000001002820b7 PyRun_SimpleFileExFlags + 391
	84  python                              0x00000001002ae7ec pymain_main + 9564
	85  python                              0x00000001000bea9d main + 125
	86  libdyld.dylib                       0x00007fff65ae9015 start + 1
	87  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

**Comment by bourque** [comment]
@jaymedina is going to look into removing the `matplotlb` dependency for the `contam_visibility.visibilityPA` method altogether.

**Comment by bourque** [comment]
Meanwhile, I have found out that specifying `matplotlib=3.0.2` in the Python 3.6 `conda` environment will avoid the error that the ExoMAST team is getting, but will get the error I put above.  So now I am not convinced that the Python version has anything to do with this.
