### ISSUE TITLE
Check that the EXOCTK_DATA environment variable is set in utils.py

### ISSUE THREAD

**Issue by JeffValenti** [ExoCTK/exoctk#258]
In utils.py, check that the EXOCTK_DATA environment variable is set between these two lines of code:

```python
EXOCTK_DATA = os.environ.get('EXOCTK_DATA')
MODELGRID_DIR = os.path.join(EXOCTK_DATA, 'modelgrid/')
```

If EXOCTK_DATA is not set, raise an exception with an informative error message. Currently, the error message is obscure:

```
(exoctk) exoctk$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from exoctk import modelgrid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/valenti/git/exoctk/exoctk/__init__.py", line 6, in <module>
    from . import modelgrid
  File "/Users/valenti/git/exoctk/exoctk/modelgrid.py", line 24, in <module>
    from . import utils
  File "/Users/valenti/git/exoctk/exoctk/utils.py", line 20, in <module>
    MODELGRID_DIR = os.path.join(EXOCTK_DATA, 'modelgrid/')
  File "/Users/valenti/mini3/envs/exoctk/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
>>> 
```

**Comment by bourque** [comment]
We should check not only that the environment variable exists but that the data that the variable is pointing to actually exists
