### ISSUE TITLE
Install failing with pyyaml

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#317]
When I do `pip install exoctk` it fails with:

```
Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.1-cp35-cp35m-macosx_10_6_x86_64.whl size=137757 sha256=0d9efeebbddf69773f589d3d99799fd9b7e2a8857e03e8d159da4df0fd11c273
  Stored in directory: /Users/jfilippazzo/Library/Caches/pip/wheels/ad/56/bc/1522f864feb2a358ea6f1a92b4798d69ac783a28e80567a18b
Successfully built pyyaml
ERROR: Error checking for conflicts.
Traceback (most recent call last):
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3012, in _parsed_pkg_info
    return self._pkg_info
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 568, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_internal/operations/check.py", line 114, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_internal/operations/check.py", line 53, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2736, in requires
    dm = self._dep_map
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3032, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3014, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jfilippazzo/miniconda3/envs/astroconda/lib/python3.5/site-packages/d2to1-0.2.12.post1.dist-info/METADATA'
Installing collected packages: jmespath, botocore, pyyaml, s3transfer, awscli, pbr, stevedore, bandit, gunicorn, cryptography, pynacl, bcrypt, paramiko, dynesty, configparser, platon, scp
  Found existing installation: PyYAML 3.12
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Some problem uninstalling PyYAML? Any ideas?

**Comment by bourque** [comment]
@hover2pi I was unable to re-create the problem.  I created a new blank `conda` environment with:

```
conda create --name exoctk-test python=3.6
pip install exoctk
```

with no issues.  I also tried creating a new `exoctk` environment with:

```
conda env create --name exoctk-test -f environment-3.6.yml
pip install exoctk
```

also with no issues.

In which environment (or lack thereof) are you trying to `pip install exoctk`?

**Comment by bourque** [comment]
There did not seem to be any install issues at our workshop, so I am going to consider this a one-off issue with @hover2pi's particular setup.
