### ISSUE TITLE
Web-version of contamination overlap "Target Name" is not, in fact, optional

### ISSUE THREAD

**Issue by nespinoza** [ExoCTK/exoctk#404]
In the online version of the Contamination Overlap tool (https://exoctk.stsci.edu/contam_visibility), if one puts in coordinates but does not define a name, an "Internal Server Error" is given to the user. A fast hack to this could be to change that variable name from None or NaN to some default if that is not given.

Update: assigning this to @catherine-martlin as per our ExoCTK team meeting (thanks @catherine-martlin!) and @bourque for backup on checking logs for tracking the problem if needed, and setting this on the v1.1 project!

N.

**Comment by hover2pi** [comment]
@nespinoza @bourque @catherine-martlin Can I take this one? I can fix it quick!

**Comment by bourque** [comment]
@hover2pi Go for it!

**Comment by hover2pi** [comment]
Hmm... looks like this is the error:

```
Traceback (most recent call last):
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.6/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/internal/data1/exodeploy/exoctk/exoctk/exoctk_app/app_exoctk.py", line 466, in contam_visibility
    title = form.targname.data or ', '.join([form.ra.data, form.dec.data])
TypeError: sequence item 0: expected str instance, decimal.Decimal found
```

Though `exoctk v1.0` has that line fixed with

```
title = form.targname.data or ', '.join([str(form.ra.data), str(form.dec.data)])
```

But the installed version on `plexoctk1` is v1.0 so somehow the change never made it into the production server. I'll update `tlexo` and see if that fixes it (though `tlexo` is down right now!) and then try it on production tonight.

**Comment by hover2pi** [comment]
Upgrading to `exoctk` v1.0 fixes this.
