### ISSUE TITLE
pandexo run_test doesn't run

### ISSUE THREAD

**Issue by melissa-hobson** [ExoCTK/exoctk#564]
Hi, I'm trying to install pandexo via github clone. The "pip install ." command runs successfully, but when I try to run the the run_test.py code it crashes with the following traceback:

```
Traceback (most recent call last):
  File "run_test.py", line 30, in <module>
    jdi.run_pandexo(exo_dict, ['NIRSpec G140H'], save_file=False)
  File "/home/hobson/Data/pandexo/pandexo/pandexo/engine/justdoit.py", line 402, in run_pandexo
    results =wrapper({"pandeia_input": inst_dict , "pandexo_input":exo}, verbose=verbose)
  File "/home/hobson/Data/pandexo/pandexo/pandexo/engine/pandexo.py", line 36, in wrapper
    return compute_full_sim(dictinput, verbose=verbose)
  File "/home/hobson/Data/pandexo/pandexo/pandexo/engine/jwst.py", line 85, in compute_full_sim
    i = InstrumentFactory(config=conf_temp)
  File "/home/hobson/venv_pandexo/lib/python3.8/site-packages/pandeia/engine/instrument_factory.py", line 50, in InstrumentFactory
    cls = inst_map[instrument](mode=mode, config=config, webapp=webapp, **kwargs)
  File "/home/hobson/venv_pandexo/lib/python3.8/site-packages/pandeia/engine/jwst.py", line 70, in __init__
    JWSTInstrument.__init__(self, mode=mode, config=config, webapp=webapp, **kwargs)
  File "/home/hobson/venv_pandexo/lib/python3.8/site-packages/pandeia/engine/jwst.py", line 33, in __init__
    telescope = JWST()
  File "/home/hobson/venv_pandexo/lib/python3.8/site-packages/pandeia/engine/config.py", line 47, in __init__
    all_config = merge_data(self._get_config(), config, dict(**kwargs))
  File "/home/hobson/venv_pandexo/lib/python3.8/site-packages/pandeia/engine/telescope.py", line 33, in _get_config
    self.ref_dir = os.path.join(default_refdata_directory, self.tel_name, "telescope")
  File "/home/hobson/anaconda3/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Any idea what could be going wrong?

**Comment by melissa-hobson** [comment]
Solved, I hadn't sourced the bash profile so it wasn't finding the refdata paths!
