### ISSUE TITLE
Log doesn't seem to be updating on production server

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#598]
The log file at `/internal/data1/log/exoctk.log` seems to have stopped updating on plexo yesterday. The site runs fine (including the LDC which seems to have been the source of the problem from the traceback below) but the log stopped updating.

```
[~]$ tail -n 100 /internal/data1/log/exoctk.log
[2024-04-24 01:48:28 -0400] [1687] [ERROR] Worker (pid:2302) was sent SIGTERM!
[2024-04-24 01:48:28 -0400] [1687] [ERROR] Worker (pid:2236) was sent SIGTERM!
[2024-04-24 01:48:28 -0400] [1687] [ERROR] Worker (pid:2247) was sent SIGTERM!
[2024-04-24 01:48:28 -0400] [1687] [ERROR] Worker (pid:2255) was sent SIGTERM!
[2024-04-24 01:48:28 -0400] [1687] [ERROR] Worker (pid:2294) was sent SIGTERM!
[2024-04-24 01:48:28 -0400] [1687] [ERROR] Worker (pid:2253) was sent SIGTERM!
[2024-04-24 01:48:28 -0400] [1687] [ERROR] Worker (pid:2257) was sent SIGTERM!
[2024-04-24 01:48:28 -0400] [1687] [ERROR] Worker (pid:2251) was sent SIGTERM!
[2024-04-24 01:48:28 -0400] [1687] [ERROR] Worker (pid:2277) was sent SIGTERM!
[2024-04-24 01:48:29 -0400] [1687] [INFO] Shutting down: Master
[2024-04-24 01:48:58 -0400] [1651] [INFO] Starting gunicorn 21.2.0
[2024-04-24 01:48:58 -0400] [1651] [INFO] Listening at: http://127.0.0.1:5000 (1651)
[2024-04-24 01:48:58 -0400] [1651] [INFO] Using worker: sync
[2024-04-24 01:48:58 -0400] [3143] [INFO] Booting worker with pid: 3143
[2024-04-24 01:48:58 -0400] [3167] [INFO] Booting worker with pid: 3167
[2024-04-24 01:48:58 -0400] [3168] [INFO] Booting worker with pid: 3168
[2024-04-24 01:48:58 -0400] [3169] [INFO] Booting worker with pid: 3169
[2024-04-24 01:48:58 -0400] [3170] [INFO] Booting worker with pid: 3170
[2024-04-24 01:48:58 -0400] [3172] [INFO] Booting worker with pid: 3172
[2024-04-24 01:48:58 -0400] [3173] [INFO] Booting worker with pid: 3173
[2024-04-24 01:48:58 -0400] [3174] [INFO] Booting worker with pid: 3174
[2024-04-24 01:48:58 -0400] [3175] [INFO] Booting worker with pid: 3175
[2024-04-24 01:48:58 -0400] [3176] [INFO] Booting worker with pid: 3176
[2024-04-24 01:48:58 -0400] [3177] [INFO] Booting worker with pid: 3177
[2024-04-24 01:48:58 -0400] [3178] [INFO] Booting worker with pid: 3178
[2024-04-24 01:48:58 -0400] [3183] [INFO] Booting worker with pid: 3183
[2024-04-24 01:48:58 -0400] [3185] [INFO] Booting worker with pid: 3185
[2024-04-24 01:48:58 -0400] [3186] [INFO] Booting worker with pid: 3186
[2024-04-24 01:48:58 -0400] [3187] [INFO] Booting worker with pid: 3187
[2024-04-24 01:48:59 -0400] [3188] [INFO] Booting worker with pid: 3188
[2024-04-24 01:48:59 -0400] [3189] [INFO] Booting worker with pid: 3189
[2024-04-24 01:48:59 -0400] [3190] [INFO] Booting worker with pid: 3190
[2024-04-24 01:48:59 -0400] [3192] [INFO] Booting worker with pid: 3192
[2024-04-24 01:48:59 -0400] [3193] [INFO] Booting worker with pid: 3193
[2024-04-24 01:48:59 -0400] [3194] [INFO] Booting worker with pid: 3194
[2024-04-24 01:48:59 -0400] [3195] [INFO] Booting worker with pid: 3195
[2024-04-24 01:48:59 -0400] [3196] [INFO] Booting worker with pid: 3196
[2024-04-24 01:48:59 -0400] [3197] [INFO] Booting worker with pid: 3197
[2024-04-24 01:48:59 -0400] [3198] [INFO] Booting worker with pid: 3198
[2024-04-24 01:48:59 -0400] [3199] [INFO] Booting worker with pid: 3199
[2024-04-24 01:48:59 -0400] [3200] [INFO] Booting worker with pid: 3200
[2024-04-24 01:48:59 -0400] [3201] [INFO] Booting worker with pid: 3201
[2024-04-24 01:48:59 -0400] [3202] [INFO] Booting worker with pid: 3202
[2024-04-24 01:48:59 -0400] [3221] [INFO] Booting worker with pid: 3221
[2024-04-24 01:48:59 -0400] [3222] [INFO] Booting worker with pid: 3222
[2024-04-30 06:17:22,802] ERROR in app: Exception on /fortney [GET]
Traceback (most recent call last):
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/internal/data1/exodeploy/exoctk/exoctk/exoctk_app/app_exoctk.py", line 143, in fortney
    fig, fh, temp_out = fortney_grid(input_args)
  File "/internal/data1/exodeploy/exoctk/exoctk/forward_models/forward_models.py", line 78, in fortney_grid
    rstar = float(args['rstar'])
ValueError: could not convert string to float: '0.458±0.013'
[2024-05-03 10:30:07,716] ERROR in app: Exception on /limb_darkening [POST]
Traceback (most recent call last):
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/internal/data1/exodeploy/exoctk/exoctk/exoctk_app/app_exoctk.py", line 727, in limb_darkening
    bandpass = Throughput(form.bandpass.data, **kwargs)
  File "/internal/data1/exodeploy/exoctk/exoctk/throughputs.py", line 39, in __init__
    super().__init__(name, filter_directory=FILT_DIR, **kwargs)
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/svo_filters/svo.py", line 253, in __init__
    self.bin(**bwargs)
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/svo_filters/svo.py", line 386, in bin
    self.pixels_per_bin = int(pts/self.n_bins)
ZeroDivisionError: division by zero
[2024-05-03 10:30:14,581] ERROR in app: Exception on /limb_darkening [POST]
Traceback (most recent call last):
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/internal/data1/exodeploy/exoctk/exoctk/exoctk_app/app_exoctk.py", line 727, in limb_darkening
    bandpass = Throughput(form.bandpass.data, **kwargs)
  File "/internal/data1/exodeploy/exoctk/exoctk/throughputs.py", line 39, in __init__
    super().__init__(name, filter_directory=FILT_DIR, **kwargs)
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/svo_filters/svo.py", line 253, in __init__
    self.bin(**bwargs)
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/svo_filters/svo.py", line 386, in bin
    self.pixels_per_bin = int(pts/self.n_bins)
ZeroDivisionError: division by zero
[2024-05-07 17:22:05 -0400] [1651] [ERROR] Worker (pid:3193) was sent SIGKILL! Perhaps out of memory?
[2024-05-07 17:22:05 -0400] [29210] [INFO] Booting worker with pid: 29210
```

**Comment by nespinoza** [comment]
Hi @hover2pi. 

First, from reading the log, it seems this has happened before; it might not be an actual memory issue, it might just be an error that triggers a SEGKILL for a worker --- not necessarily memory.

Second, the log _is_ working, but currently only logs errors --- not general usage (perhaps we should document this so people don't get confused in the future). I just did a test with an error I know is happening --- e.g., go to the Contamination Overlap tool and try to get the visibility with NIRspec. It fails, and that is correctly logged (I'll open an Issue on this BTW --- will ping @mfixstsci as this seems to be a visibility tool thing):

`[2024-05-08 11:50:05,990] ERROR in app: Exception on /contam_visibility [POST]`

So I think we can call this issue done. Still, we need to investigate the contam overlap :).

N.

**Comment by nespinoza** [comment]
As we discussed internally, there _seems_ to be a communication problem between the Contam Overlap SOSS tool and the log (ie, errors not being logged).

**Comment by hover2pi** [comment]
Log is now working.
