### ISSUE TITLE
Production crashes for invalid field values in Forward Models

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#602]
The production log shows it crashes when a user doesn't put numbers in the parameter fields in the Forward Models calculator. Add a type check and throw a validation error instead. Traceback:

```
Traceback (most recent call last):
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/internal/data1/anaconda3/envs/exoctk-3.10/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/internal/data1/exodeploy/exoctk/exoctk/exoctk_app/app_exoctk.py", line 143, in fortney
    fig, fh, temp_out = fortney_grid(input_args)
  File "/internal/data1/exodeploy/exoctk/exoctk/forward_models/forward_models.py", line 82, in fortney_grid
    temp = float(args['temp'])
ValueError: could not convert string to float: ''
```

**Comment by hover2pi** [comment]
Fixed in #597
