### ISSUE TITLE
Running sphinx to build the Readthedocs page has errors

### ISSUE THREAD

**Issue by catherine-martlin** [ExoCTK/ExoCTK#97]
```sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.3
/Users/cmartlin/anaconda2/envs/exoctk/lib/python3.5/site-packages/Sphinx-1.6.3-py3.5.egg/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
  RemovedInSphinx17Warning)
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.h5py.org/en/latest/objects.inv...
loading intersphinx inventory from http://docs.astropy.org/en/stable/objects.inv...
loading intersphinx inventory from /user/cmartlin/exoCTK/ExoCTK/astropy_helpers/astropy_helpers/sphinx/local/python3_local_links.inv...
loading intersphinx inventory from http://docs.scipy.org/doc/numpy/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/numpy/objects.inv -> https://docs.scipy.org/doc/numpy/objects.inv
loading intersphinx inventory from http://matplotlib.org/objects.inv...
intersphinx inventory has moved: http://matplotlib.org/objects.inv -> https://matplotlib.org/objects.inv
loading intersphinx inventory from http://docs.python.org/3/objects.inv...
intersphinx inventory has moved: http://docs.python.org/3/objects.inv -> https://docs.python.org/3/objects.inv
loading intersphinx inventory from http://docs.scipy.org/doc/scipy/reference/objects.inv...
intersphinx inventory has moved: http://docs.scipy.org/doc/scipy/reference/objects.inv -> https://docs.scipy.org/doc/scipy/reference/objects.inv
[autosummary] generating autosummary for: core/index.rst, index.rst, ldc/ldcfit/index.rst, ldc/ldcplot/index.rst, pal/exotransmit.rst, pal/forward_models.rst

Exception occurred:
  File "/user/cmartlin/exoCTK/ExoCTK/astropy_helpers/astropy_helpers/sphinx/ext/automodsumm.py", line 311, in automodsumm_to_autosummary_lines
    if 'astropy_helpers.sphinx.ext.automodapi' in app._extensions:
AttributeError: 'Sphinx' object has no attribute '_extensions'
The full traceback has been saved in /var/folders/pb/3njrmjd93mvgkjm9y7wc75l80001k5/T/sphinx-err-uxhlodwc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:44: html] Error 1```

**Comment by catherine-martlin** [comment]
I looked into it some and it seems that the Sphinx update caused some issues with astropy_helpers: astropy/sphinx-automodapi#22

**Comment by catherine-martlin** [comment]
Interestingly, when I updated to Sphinx 1.7.6 there is a different error:

sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.6

Extension error:
Could not import extension astropy_helpers.sphinx.ext.numpydoc (exception: cannot import name 'Directive')
make: *** [Makefile:44: html] Error 2

**Comment by catherine-martlin** [comment]
And, when I try with the version of Sphinx used to last build our readthedocs I get:

```sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.5

Extension error:
Could not import extension sphinx.builders.latex (exception: cannot import name 'new_document')
make: *** [Makefile:44: html] Error 1

**Comment by catherine-martlin** [comment]
Having gone through the start of this tutorial (http://docs.sphinxdocs.com/en/latest/start.html) I'm starting to get it maybe. I think I have an import error currently because when I try to run `make html` on my fork of the branch I am nor getting this error: 

```(ExoCTK) swarthmore:docs cmartlin$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.6

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/Users/cmartlin/anaconda2/envs/ExoCTK/lib/python3.5/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/Users/cmartlin/anaconda2/envs/ExoCTK/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 84, in <module>
    __import__(setup_cfg['package_name'])
  File "/Users/cmartlin/anaconda2/envs/ExoCTK/lib/python3.5/site-packages/ExoCTK-0.1.3.dev769-py3.5-macosx-10.7-x86_64.egg/ExoCTK/__init__.py", line 17, in <module>
    from . import forward_models
  File "/Users/cmartlin/anaconda2/envs/ExoCTK/lib/python3.5/site-packages/ExoCTK-0.1.3.dev769-py3.5-macosx-10.7-x86_64.egg/ExoCTK/forward_models/__init__.py", line 5, in <module>
    from . import exotransmit
  File "/Users/cmartlin/anaconda2/envs/ExoCTK/lib/python3.5/site-packages/ExoCTK-0.1.3.dev769-py3.5-macosx-10.7-x86_64.egg/ExoCTK/forward_models/exotransmit.py", line 2, in <module>
    from . import _exotransmit_wrapper
ImportError: cannot import name '_exotransmit_wrapper'

make: *** [Makefile:44: html] Error 2

**Comment by catherine-martlin** [comment]
I think this may trace back to changes in astropy_helpers - https://github.com/ribozz/sphinx-argparse/issues/65

We are still using a version of astropy_helpers.sphinx.ext.numpydoc that calls `from sphinx.util.compat import Directive`

**Comment by catherine-martlin** [comment]
I've now run things on our most recent master branch and have a version of Read the Docs that will need to be flushed out but that has all the correct modules and submodules. See #111 .
